### ISSUE TITLE
Include .bib in NotesTeX

### ISSUE THREAD

**Issue by rcv-legado** [Adhumunt/NotesTeX#1]
Dear, Aditya Dhumuntarao, how are you?
-------------------------------
**Questions about:**
Could you show (if possible an example) how to include .bib file in notestex?
-------------------------------
**My updates in NotesTeX:**
I'm modifying the .sty file into Portuguese and include the following lines:
\usepackage[utf8]{inputenc}
\usepackage[portuguese]{babel}

and include the following line (\NotesTeX):
\newcommand{\NotesTeX}{\textsc{N\kern-0.1emo\kern-0.017emtes}\kern-0.15em\TeX} %logo notestex

**Comment by Adhumunt** [comment]
Hello Ricardo,

Great question. Bibliographies will need to be implemented into NotesTeX, specifically margin adjustment. At the moment, I suggest reading the [Jhep.bst](https://jhep.sissa.it/jhep/help/JHEP_TeXclass.jsp) file on the SISSA site. Try to use BibTeX for your bibliography needs (.bst files).

With regards to your updates, I'll write up a MWE for people wanting to implement different languages and add it to the project main page. Nice suggestion.

Oh, and the \NotesTeX command is awesome. When I return from vacation I'll have to check this out.

Cheers,
Aditya

**Comment by Adhumunt** [comment]
Hello Ricardo,

I have fixed the issues with .bib files. Here is a minimal working example of incorporating a .bib file using NotesTeX:

```latex
\documentclass[10pt]{article}
\usepackage{/Path/to/package/NotesTeX} %/Path/to/package should be replaced with package location
\usepackage{lipsum}

\begin{document}
  \lipsum[1]
  \section{Subtest Section 1}
  Some notes here\sn{With some additional sidenotes.} and one citation here \cite{A Citation from Your.bib}.

  {
    \bibliographystyle{unsrt}
    \bibliography{Your.bib}
  }

\end{document}
```

If you provide a .bib file, then citations simply given by the above example! Sorry this took a while.
