### ISSUE TITLE
Define customize blocks

### ISSUE THREAD

**Issue by ShaoxiongYao** [Adhumunt/NotesTeX#2]
May I ask is it possible to define customize blocks?
Since I want to define new blocks like a corollary, proposition.

**Comment by yp51md** [comment]
Please try to add this code to your `NotesTex.sty` and replace `mz` and `Math Zone` with your preferred block‘s name.
```
\theoremstyle{mystyle}{
     \newtheorem*{mz}{Math Zone}
}
\tcolorboxenvironment{mz}{
  boxrule=0pt,
  boxsep=2pt,
  colback={red!15!white},
  enhanced jigsaw, 
  borderline west={2pt}{0pt}{red!75!black},
  sharp corners,
  before skip=10pt,
  after skip=10pt,
  breakable,
}
```

**Comment by Adhumunt** [comment]
Hi Shaoxiong,

Additional amsthm environments have been included in the v3.
