### ISSUE TITLE
The suffix "V3" in style file name

### ISSUE THREAD

**Issue by FallenSky2077** [Adhumunt/NotesTeX#5]
The file "NotesTeX.tex" in zip has the following code in preamble area
``` latex
\usepackage{NotesTeXV3,lipsum}
```
However, the style file in the same zip is named "NotesTeX.sty" without the suffix "V3", although it provides package by
``` latex
\ProvidesPackage{NotesTeXV3}[2021/10/22 rV3]
```

My compilation failed and got following error message:

> LaTeX Error: File `NotesTeXV3.sty' not found.

After I delete "V3" suffix, the compilation can be completed normally. I am not sure what is the 
expected behavior of these different names. 

My latex distribution is texlive in archlinux with version 2021.58710-2.

**Comment by Adhumunt** [comment]
@FallenSky2077 Thanks for pointing that out, I've fixed the issue now by updating the suffix.
